watch:
  asset: BTC
  currency: USDT
  mode: importer # backtest | importer | realtime
  tickrate: 500
  fillGaps: empty
  daterange:
    start: '2017-10-01T00:00:00.000Z'
    end: '2025-11-01T00:00:00.000Z'

exchange:
  name: binance

storage:
  type: sqlite
  database: ./db/binance-BTC_USDT.sql

plugins:
  - name: CandleWriter
