watch:
  assets:
    - BTC
  currency: USDT
  timeframe: 1m
  mode: realtime

exchange:
  name: binance

storage:
  type: sqlite
  database: ./db/binance-BTC_USDT.sql

plugins:
  - name: CandleWriter
